sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
services:
    - docker
cache:
  directories:
  - node_modules
before_install:
- cd server; npm update
install:
- cd server; npm install
script:
- cd server; npm test; npm run coveralls
