language: node_js
os:
  - 'linux'
node_js:
  - '12'
branches:
  only:
  - '/.*/'
services:
    - docker
cache:
  directories:
  - node_modules
script:
  - npm i -g codecov
  - docker-compose run server npm run test:cov
  - bash <(curl -s https://codecov.io/bash)
