sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
services:
    - docker
cache:
  directories:
  - node_modules
script:
    - docker-compose run server npm run test:cov
