sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
services:
    - docker
cache:
  directories:
  - node_modules
before_install:
- npm update
- docker-compose up --build
install:
- npm install
script:
- npm test
- npm run coveralls
